#  Supabase Database Configuration
spring:
  datasource:

    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres

    # The pooler username is always 'postgres'
    username: postgres.qtflknlzetklgkbdibpf
    # This is the password you set when you created the project
    password: -_V3ry-_-Tru3-_-M0m3nt$_-

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  google:
    ai:
      api-key: [ YOUR_GOOGLE_AI_STUDIO_API_KEY_HERE ]